-- ============================================================================
-- CREATE CORE SCHEMA
-- Generated by HIMS Platform Monorepo Template
-- ============================================================================
-- 
-- This migration creates the core schema with:
-- - Core platform tables (tenants, users, etc.)
-- - RLS enablement
-- - Session variable setup
-- 
-- This is a foundational schema that all modules depend on.
-- ============================================================================

-- Create core schema
CREATE SCHEMA IF NOT EXISTS core;

-- Set search path
SET search_path TO core;

-- ============================================================================
-- CORE TABLES
-- ============================================================================

-- Tenants table (required for multi-tenancy)
CREATE TABLE IF NOT EXISTS core.tenants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Metadata
    metadata JSONB,
    
    CONSTRAINT tenants_slug_check CHECK (slug ~ '^[a-z0-9-]+$')
);

-- Users table (required for authentication)
CREATE TABLE IF NOT EXISTS core.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    external_id VARCHAR(255), -- Scalekit user ID
    status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- Name (JSONB for FHIR HumanName compatibility)
    name JSONB,
    
    CONSTRAINT users_tenant_id_fk FOREIGN KEY (tenant_id) 
        REFERENCES core.tenants(id) ON DELETE CASCADE,
    CONSTRAINT users_email_tenant_unique UNIQUE (email, tenant_id)
);

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_users_tenant_id ON core.users(tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON core.users(email);
CREATE INDEX IF NOT EXISTS idx_users_external_id ON core.users(external_id);

-- ============================================================================
-- ROW LEVEL SECURITY (RLS)
-- ============================================================================
-- Core schema tables may or may not need RLS depending on requirements
-- For now, we enable RLS on users table for tenant isolation
-- ============================================================================

ALTER TABLE core.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_tenant_isolation_policy ON core.users
    FOR ALL
    USING (tenant_id::text = current_setting('app.current_tenant', true))
    WITH CHECK (tenant_id::text = current_setting('app.current_tenant', true));

-- ============================================================================
-- FUNCTIONS FOR SESSION VARIABLES
-- ============================================================================
-- These functions help set and get session variables used by RLS policies
-- ============================================================================

-- Function to ensure session variables are set
CREATE OR REPLACE FUNCTION core.ensure_session_variables()
RETURNS void AS $$
BEGIN
    -- This function is called by MultiTenantConnectionProvider
    -- It ensures app.current_tenant and app.current_user are set
    -- If not set, it will cause RLS policies to fail (by design)
    IF current_setting('app.current_tenant', true) IS NULL THEN
        RAISE EXCEPTION 'app.current_tenant session variable must be set';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- GRANTS
-- ============================================================================

-- Create application role if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'application_role') THEN
        CREATE ROLE application_role;
    END IF;
END
$$;

-- Grant usage on schema
GRANT USAGE ON SCHEMA core TO application_role;

-- Grant privileges on tables
GRANT SELECT, INSERT, UPDATE, DELETE ON core.tenants TO application_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON core.users TO application_role;

-- ============================================================================
-- INITIAL DATA (Optional)
-- ============================================================================
-- Uncomment to create a default tenant for development
-- 
-- INSERT INTO core.tenants (id, name, slug, status)
-- VALUES ('00000000-0000-0000-0000-000000000001', 'Default Tenant', 'default', 'ACTIVE')
-- ON CONFLICT DO NOTHING;
-- ============================================================================

