apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.platformName | lower }}
  description: {{ values.description | default("HIMS Platform Monorepo") }}
  
  annotations:
    # Link to the Git repo
    github.com/project-slug: {{ values.repoUrl | replace("https://github.com/", "") | replace(".git", "") }}
    
    # Platform type
    backstage.io/techdocs-ref: dir:.
    
spec:
  type: service
  lifecycle: experimental
  owner: {{ values.owner | default("platform-team") }}
  {% if values.system %}
  system: {{ values.system }}
  {% endif %}

