apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ values.platformName }}
  description: {{ values.description }}
  
  annotations:
    # Link to the Git repo
    github.com/project-slug: ${{ values.repoUrl | parseRepoUrl | pick('owner') }}/${{ values.repoUrl | parseRepoUrl | pick('repo') }}
    
    # Platform type
    backstage.io/techdocs-ref: dir:.
    
spec:
  type: service
  lifecycle: experimental
  owner: {{ values.owner }}
  system: {{ values.system }}
  
  # Platform consists of multiple services
  providesApis:
    - api:default/{{ values.platformName }}-backend-api
    - api:default/{{ values.platformName }}-frontend-api
  
  dependsOn:
    - resource:default/postgres-{{ values.postgresDbName }}
    - resource:default/redis-{{ values.platformName }}-cache
    - resource:default/kafka-{{ values.platformName }}

